stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        echo "Test"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment/configmap.yaml
  - applyYamlConfig:
      path: ./deployment/deployment.yaml