stages:
- name: Build
  when:
      branch: master
      event: [ push, pull_request ]
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: echo "Test"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment/service-account.yaml
  - applyYamlConfig:
      path: ./deployment/configmap.yaml
  - applyYamlConfig:
      path: ./deployment/deployment.yaml
branch:
  include:
  - master
  - feature/*
notification: {}
