apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kamus-example
  namespace: default2
  labels:
    app: kamus-example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kamus-example
    spec:
      serviceAccountName: kamus-example-sa1
      automountServiceAccountToken: true
      initContainers:
        - name: "kamus-init"
          image: "soluto/kamus-init-container:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: KAMUS_URL
              value: http://decrypt.default.100.76.70.251.xip.io/
          volumeMounts:
          - name: encrypted-secrets
            mountPath: /encrypted-secrets
          - name: decrypted-secrets
            mountPath: /decrypted-secrets
          args: ["-e","/encrypted-secrets","-d","/decrypted-secrets", "-n", "config.json"]
      containers:
        - name: app
          image: soluto/kamus-example-app
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: decrypted-secrets
            mountPath: /secrets
      volumes:
        - name: encrypted-secrets
          configMap: 
            name: encrypted-secrets-cm
        - name: decrypted-secrets
          emptyDir:
            medium: Memory
